version: "3"

services:
    nginx:
        build: 
           context: /usr/local/docker/nginx
           dockerfile: Dockerfile
        restart: always
        environment:
                TZ: "Asia/Seoul"
        ports: 
                - "80:80"
        volumes: 
                - "nginx_volume:/etc/nginx"
                - "nginx_ssh_volume:/root"
                #- "/usr/local/docker/nginx/build:/usr/local/build"
                - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
              dnabro_net:
                      ipv4_address: 172.19.0.2
        container_name: nginxContainer

    jenkins:
         image: cbb1017/jenkinsorg
         #build:
           #context: /usr/local/docker/jenkins
           #dockerfile: Dockerfile
         restart: always 
         volumes:
                 - "jenkins_volume:/var/jenkins_home"
                 - "jenkins_ssh_volume:/root"
                 - "/var/run/docker.sock:/var/run/docker.sock"
         environment:
                 TZ: "Asia/Seoul"
         ports:
                 - "7009:8080"
                 - "50000:50000"
         container_name: jenkinscontainer
         networks: 
               dnabro_net:
                        ipv4_address: 172.19.0.3
                        #   mariadb:
                        #         build:
                        #          context: /usr/local/docker/mariadb
                        #   dockerfile: Dockerfile
                        #     args:
                        # buildno: 1.0
                        #container_name: maridbcontainer
                        #restart: always
                        # volumes: 
                        #   - "db_volume:/var/lib/mysql"
                        #      - "db_volume:/etc"
                        #   environment:
                        #     TZ: "Asia/Seoul"
                        #       ports:
                        #   - "3307:3306"
volumes: 
   db_volume:
   nginx_volume:
   nginx_ssh_volume:
   jenkins_volume:
   jenkins_ssh_volume:
   
networks:
   dnabro_net:
        external: true

